// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-2-SUcxM1iHuPVxWqqDcb696QYXSe_Bc',
    appId: '1:189985937924:web:76f783f40d521040fe7351',
    messagingSenderId: '189985937924',
    projectId: 'graphic-boulder-312612',
    authDomain: 'graphic-boulder-312612.firebaseapp.com',
    storageBucket: 'graphic-boulder-312612.appspot.com',
    measurementId: 'G-QKM3YGC6K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQgeGqtJbCS5pvEZL8_4eD0Vc1j-uVolg',
    appId: '1:189985937924:android:4e08ddd8b9067a77fe7351',
    messagingSenderId: '189985937924',
    projectId: 'graphic-boulder-312612',
    storageBucket: 'graphic-boulder-312612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgD0GFTAblaO7F_NcpgAmC5gCYcXaUJYk',
    appId: '1:189985937924:ios:1b3d42b1d91add4afe7351',
    messagingSenderId: '189985937924',
    projectId: 'graphic-boulder-312612',
    storageBucket: 'graphic-boulder-312612.appspot.com',
    iosClientId: '189985937924-m2lgkdq2is9ft7hdlessphkqk17omhs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgD0GFTAblaO7F_NcpgAmC5gCYcXaUJYk',
    appId: '1:189985937924:ios:1b3d42b1d91add4afe7351',
    messagingSenderId: '189985937924',
    projectId: 'graphic-boulder-312612',
    storageBucket: 'graphic-boulder-312612.appspot.com',
    iosClientId: '189985937924-m2lgkdq2is9ft7hdlessphkqk17omhs0.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
